/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-12-23 06:28:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class simulater_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:containsIgnoreCase", org.apache.taglibs.standard.functions.Functions.class, "containsIgnoreCase", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1701994853679L));
    _jspx_dependants.put("jar:file:/C:/tools/teamproj/workspace_proj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/carina/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/tools/teamproj/workspace_proj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/carina/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1694412638883L));
    _jspx_dependants.put("/WEB-INF/inc/top.jsp", Long.valueOf(1703312916882L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>시뮬레이터</title>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/button3.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<link rel=\"canonical\"\r\n");
      out.write("	href=\"https://themesberg.com/product/ui-kits/neumorphism-ui/\">\r\n");
      out.write("<!--  Social tags -->\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("	content=\"neumorphism, neumorphism ui, neomorphism, neomorphism ui, neomorphism css, neumorphism css, neumorph, neumorphic, design system, login, form, table, tables, card, cards, navbar, modal, icons, icons, map, chat, carousel, menu, datepicker, gallery, slider, date, social, dropdown, search, tab, nav, footer, date picker, forms, tabs, time, button, select, input, timeline, cart, about us, account, log in, blog, profile, portfolio, landing page, ecommerce, shop, landing, register, app, contact, one page, sign up, signup, store, bootstrap 4, bootstrap4, dashboard, bootstrap 4 dashboard, bootstrap 4 design, bootstrap 4 system, bootstrap 4, bootstrap 4 uit kit, bootstrap 4 kit, themesberg, html kit, html css template, web template, bootstrap, bootstrap 4, css3 template, frontend, responsive bootstrap template, bootstrap ui kit, responsive ui kit\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("	content=\"Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.\">\r\n");
      out.write("<!-- Schema.org markup for Google+ -->\r\n");
      out.write("<meta itemprop=\"name\" content=\"Neumorphism UI by Themesberg\">\r\n");
      out.write("<meta itemprop=\"description\"\r\n");
      out.write("	content=\"Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.\">\r\n");
      out.write("<meta itemprop=\"image\"\r\n");
      out.write("	content=\"https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg\">\r\n");
      out.write("<!-- Twitter Card data -->\r\n");
      out.write("<meta name=\"twitter:card\" content=\"product\">\r\n");
      out.write("<meta name=\"twitter:site\" content=\"@themesberg\">\r\n");
      out.write("<meta name=\"twitter:title\" content=\"Neumorphism UI by Themesberg\">\r\n");
      out.write("<meta name=\"twitter:description\"\r\n");
      out.write("	content=\"Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.\">\r\n");
      out.write("<meta name=\"twitter:creator\" content=\"@themesberg\">\r\n");
      out.write("<meta name=\"twitter:image\"\r\n");
      out.write("	content=\"https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg\">\r\n");
      out.write("<!-- Open Graph data -->\r\n");
      out.write("<meta property=\"fb:app_id\" content=\"214738555737136\">\r\n");
      out.write("<meta property=\"og:title\" content=\"Neumorphism UI by Themesberg\">\r\n");
      out.write("<meta property=\"og:type\" content=\"article\">\r\n");
      out.write("<meta property=\"og:url\"\r\n");
      out.write("	content=\"https://demo.themesberg.com/neumorphism-ui/\">\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("	content=\"https://themesberg.s3.us-east-2.amazonaws.com/public/products/neumorphism-ui/neumorphism-thumbnail.jpg\">\r\n");
      out.write("<meta property=\"og:description\"\r\n");
      out.write("	content=\"Start developing neumorphic web applications and pages using Neumorphism UI. It features over 100 individual components and 5 example pages.\">\r\n");
      out.write("<meta property=\"og:site_name\" content=\"Themesberg\">\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"120x120\"\r\n");
      out.write("	href=\"assets/img/favicon/apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\"\r\n");
      out.write("	href=\"assets/img/favicon/favicon-32x32.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\r\n");
      out.write("	href=\"assets/img/favicon/favicon-16x16.png\">\r\n");
      out.write("<link rel=\"manifest\" href=\"assets/img/favicon/site.webmanifest\">\r\n");
      out.write("<link rel=\"mask-icon\" href=\"assets/img/favicon/safari-pinned-tab.svg\"\r\n");
      out.write("	color=\"#FFFFFF\">\r\n");
      out.write("<meta name=\"msapplication-TileColor\" content=\"#FFFFFF\">\r\n");
      out.write("<meta name=\"theme-color\" content=\"#FFFFFF\">\r\n");
      out.write("<!-- Fontawesome -->\r\n");
      out.write("<link type=\"text/css\"\r\n");
      out.write("	href=\"resources/vendor/@fortawesome/fontawesome-free/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Pixel CSS -->\r\n");
      out.write("<link type=\"text/css\" href=\"css/neumorphism.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- NOTICE: You can use the _analytics.html partial to include production code specific code & trackers -->\r\n");
      out.write("<!-- Global site tag (gtag.js) - Google Analytics -->\r\n");
      out.write("<script async\r\n");
      out.write("	src=\"https://www.googletagmanager.com/gtag/js?id=UA-141734189-1\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	window.dataLayer = window.dataLayer || [];\r\n");
      out.write("	function gtag() {\r\n");
      out.write("		dataLayer.push(arguments);\r\n");
      out.write("	}\r\n");
      out.write("	gtag('js', new Date());\r\n");
      out.write("	gtag('config', 'UA-141734189-1');\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Navigation-->\r\n");
      out.write("<!-- 네비 바 시작 -->\r\n");
      out.write("<nav id=\"navbar-main\" aria-label=\"Primary navigation\"\r\n");
      out.write("	class=\"navbar navbar-main navbar-expand-lg navbar-theme-primary headroom navbar-light\">\r\n");
      out.write("	<!-- 로고 넣는 부분 -->\r\n");
      out.write("	<div class=\"container position-relative\">\r\n");
      out.write("		<a\r\n");
      out.write("			class=\"navbar-brand shadow-soft py-2 px-3 rounded border border-light mr-lg-4\"\r\n");
      out.write("			href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">CARINA</a>\r\n");
      out.write("		<div class=\"navbar-collapse collapse\" id=\"navbar_global\">\r\n");
      out.write("			<div class=\"navbar-collapse-header\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-6 collapse-brand\"></div>\r\n");
      out.write("					<div class=\"col-6 collapse-close\">\r\n");
      out.write("						<a href=\"#navbar_global\" class=\"fas fa-times\"\r\n");
      out.write("							data-toggle=\"collapse\" data-target=\"#navbar_global\"\r\n");
      out.write("							aria-controls=\"navbar_global\" aria-expanded=\"false\" title=\"close\"\r\n");
      out.write("							aria-label=\"Toggle navigation\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<ul class=\"navbar-nav  navbar-nav-hover align-items-lg-center \">\r\n");
      out.write("				<li class=\"nav-item shadow-soft rounded\"><a\r\n");
      out.write("					href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" class=\"nav-link\" data-toggle=\"\"><span\r\n");
      out.write("						class=\"nav-link-inner-text\">지역별 탄소 배출량 </span></a></li>\r\n");
      out.write("				<li class=\"nav-item shadow-soft rounded\"><a\r\n");
      out.write("					href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" class=\"nav-link\" data-toggle=\"\"><span\r\n");
      out.write("						class=\"nav-link-inner-text\">환경 MBTI</span></a></li>\r\n");
      out.write("				<li class=\"nav-item shadow-soft rounded\"><a\r\n");
      out.write("					href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" class=\"nav-link\" data-toggle=\"\"><span\r\n");
      out.write("						class=\"nav-link-inner-text\">탄소 배출량 시뮬레이터</span></a></li>\r\n");
      out.write("				<li class=\"nav-item dropdown shadow-soft rounded\"><a href=\"#\"\r\n");
      out.write("					class=\"nav-link\" data-toggle=\"dropdown\"><span\r\n");
      out.write("						class=\"nav-link-inner-text\">전력 예측 모델</span> <span\r\n");
      out.write("						class=\"fas fa-angle-down nav-link-arrow ml-2\"></span></a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">우리 동네 전력량 예측하기</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\">탄소 중립 솔루션</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li class=\"nav-item dropdown shadow-soft rounded\"><a href=\"#\"\r\n");
      out.write("					class=\"nav-link shadow-soft rounded\" data-toggle=\"dropdown\"><span\r\n");
      out.write("						class=\"nav-link-inner-text\">게시판</span> <span\r\n");
      out.write("						class=\"fas fa-angle-down nav-link-arrow ml-2\"></span></a>\r\n");
      out.write("					<ul class=\"dropdown-menu\">\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\">실천 일지</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\">환경\r\n");
      out.write("								뉴스</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\"\r\n");
      out.write("							href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\">자유 게시판</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		<!-- 로그인 구현시 세션 정보에 따라 다르게 보이게 설정해야 함  -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"d-flex align-items-center\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<button class=\"navbar-toggler ml-2\" type=\"button\"\r\n");
      out.write("				data-toggle=\"collapse\" data-target=\"#navbar_global\"\r\n");
      out.write("				aria-controls=\"navbar_global\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("     <style>\r\n");
      out.write("		/* 간단한 스타일링 */\r\n");
      out.write("		body {\r\n");
      out.write("			\r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#tabContainer {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			margin: 20px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.tab {\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			margin: 0 10px;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("			background-color: #ddd;\r\n");
      out.write("			border: 1px solid #ccc;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.tab.active {\r\n");
      out.write("			background-color: #bbb;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.usageInput {\r\n");
      out.write("			display: none;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#calculator {\r\n");
      out.write("			width: 1000px;\r\n");
      out.write("			height: 500px;\r\n");
      out.write("			margin: 20px auto;\r\n");
      out.write("			border: 1px solid #ccc;\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		input {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			margin-bottom: 10px;\r\n");
      out.write("			padding: 8px;\r\n");
      out.write("			box-sizing: border-box;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		button {\r\n");
      out.write("			width: 30%;\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			box-sizing: border-box;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#totalResult {\r\n");
      out.write("			margin-top: 20px; /* 상단 여백 조절 */\r\n");
      out.write("			text-align: center; /* 가운데 정렬 */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#totalResult p {\r\n");
      out.write("			margin: 10px 0; /* 각각의 p 태그에 상하 여백 조절 */\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			font-size: 1.1em;\r\n");
      out.write("			color: #333;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#totalResult span {\r\n");
      out.write("			font-weight: bold; /* 숫자 부분을 굵게 표시 */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#result {\r\n");
      out.write("			margin-top: 20px; /* 상단 여백 조절 */\r\n");
      out.write("			text-align: center; /* 가운데 정렬 */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#result p {\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			margin: 10px 0; /* 각각의 p 태그에 상하 여백 조절 */\r\n");
      out.write("			font-size: 1.1em;\r\n");
      out.write("			color: #333;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#result span {\r\n");
      out.write("			font-weight: bold; /* 숫자 부분을 굵게 표시 */\r\n");
      out.write("		}\r\n");
      out.write("</style>\r\n");
      out.write("    <script>\r\n");
      out.write("        // 초기 탭 설정\r\n");
      out.write("        var currentTab = 'electricity';\r\n");
      out.write("        var tabResults = {};\r\n");
      out.write("        var electricityEmission = 0;\r\n");
      out.write("        var gasEmission = 0;\r\n");
      out.write("        var waterEmission = 0;\r\n");
      out.write("        var totalCarbonEmission = 0;\r\n");
      out.write("        var totalTreeConversion = 0;\r\n");
      out.write("       \r\n");
      out.write("        // 계수를 탭에 따라 동적으로 결정\r\n");
      out.write("        function getCoefficient(tabName) {\r\n");
      out.write("            switch (tabName) {\r\n");
      out.write("                case 'electricity':\r\n");
      out.write("                    return 0.424;\r\n");
      out.write("                case 'gas':\r\n");
      out.write("                    return 21.5;\r\n");
      out.write("                case 'water':\r\n");
      out.write("                    return 0.3;\r\n");
      out.write("                default:\r\n");
      out.write("                    return 0; // 기본값\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 탭에 따른 제목 반환 함수\r\n");
      out.write("        function getTabTitle(tabName) {\r\n");
      out.write("            switch (tabName) {\r\n");
      out.write("                case 'electricity':\r\n");
      out.write("                    return '전기 사용량에 따른 탄소배출량과 나무 환산';\r\n");
      out.write("                case 'gas':\r\n");
      out.write("                    return '가스 사용량에 따른 탄소배출량과 나무 환산';\r\n");
      out.write("                case 'water':\r\n");
      out.write("                    return '수도 사용량에 따른 탄소배출량과 나무 환산';\r\n");
      out.write("                default:\r\n");
      out.write("                    return '';\r\n");
      out.write("            }\r\n");
      out.write("        }      \r\n");
      out.write("\r\n");
      out.write("        function calculateResult() {\r\n");
      out.write("        	console.log(\"현재탭 :\" + currentTab);\r\n");
      out.write("    \r\n");
      out.write("            var inputId = currentTab + 'Usage';\r\n");
      out.write("            var usageInput = document.getElementById(inputId);\r\n");
      out.write("            	console.log(usageInput);\r\n");
      out.write("\r\n");
      out.write("            if (usageInput) {\r\n");
      out.write("                var usage = parseFloat(usageInput.value);\r\n");
      out.write("				console.log(\"usage :\" + usage);\r\n");
      out.write("                // 탄소배출량 및 나무 환산 계산\r\n");
      out.write("                var carbonEmission = usage * getCoefficient(currentTab);\r\n");
      out.write("                var treeConversion = carbonEmission / 7.5;\r\n");
      out.write("\r\n");
      out.write("                // 결과 표시\r\n");
      out.write("                var carbonEmissionElement = document.getElementById('carbonEmission');\r\n");
      out.write("                var treeConversionElement = document.getElementById('treeConversion');\r\n");
      out.write("                var totalCarbonEmissionElement = document.getElementById('totalCarbonEmission');\r\n");
      out.write("                var totalTreeConversionElement = document.getElementById('totalTreeConversion');\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                if (carbonEmissionElement && treeConversionElement && totalCarbonEmissionElement && totalTreeConversionElement) {\r\n");
      out.write("                    carbonEmissionElement.textContent = carbonEmission.toFixed(2);\r\n");
      out.write("                    treeConversionElement.textContent = treeConversion.toFixed(2);\r\n");
      out.write("\r\n");
      out.write("                    // 현재 탭의 결과 저장\r\n");
      out.write("                    tabResults[currentTab] = {\r\n");
      out.write("                        carbonEmission: carbonEmission,\r\n");
      out.write("                        treeConversion: treeConversion\r\n");
      out.write("                    };\r\n");
      out.write("\r\n");
      out.write("                    // 전체 탭의 총 결과 계산\r\n");
      out.write("                     totalCarbonEmission = 0;\r\n");
      out.write("                     totalTreeConversion = 0;\r\n");
      out.write("\r\n");
      out.write("                    // 각 탭의 결과를 누적\r\n");
      out.write("                    for (var tab in tabResults) {\r\n");
      out.write("                        if (tabResults.hasOwnProperty(tab)) {\r\n");
      out.write("                            totalCarbonEmission += tabResults[tab].carbonEmission || 0;\r\n");
      out.write("                            totalTreeConversion += tabResults[tab].treeConversion || 0;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // 총 결과 표시\r\n");
      out.write("                    totalCarbonEmissionElement.textContent = totalCarbonEmission.toFixed(2);\r\n");
      out.write("                    totalTreeConversionElement.textContent = totalTreeConversion.toFixed(2);\r\n");
      out.write("                    // 전체 탭의 결과에서 탄소배출량 값 가져오기\r\n");
      out.write("                    electricityEmission = tabResults['electricity'] ? tabResults['electricity'].carbonEmission : 0;\r\n");
      out.write("                    gasEmission = tabResults['gas'] ? tabResults['gas'].carbonEmission : 0;\r\n");
      out.write("                    waterEmission = tabResults['water'] ? tabResults['water'].carbonEmission : 0;\r\n");
      out.write("                   \r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            } else {\r\n");
      out.write("                console.error('Usage input element not found.');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("   \r\n");
      out.write("     // 탭 변경 함수\r\n");
      out.write("        function changeTab(tabName) {\r\n");
      out.write("            // 탭 활성화 및 비활성화\r\n");
      out.write("            var tabs = document.querySelectorAll('.tab');\r\n");
      out.write("            tabs.forEach(function (tab) {\r\n");
      out.write("                tab.classList.remove('active');\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            var selectedTab = document.querySelector('.tab.' + tabName);\r\n");
      out.write("            selectedTab.classList.add('active');\r\n");
      out.write("\r\n");
      out.write("            // 입력 요소 활성화 및 비활성화\r\n");
      out.write("            var inputContainers = document.querySelectorAll('.usageInput');\r\n");
      out.write("            inputContainers.forEach(function (container) {\r\n");
      out.write("                container.style.display = 'none';\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            var selectedInputContainer = document.querySelector('.' + tabName + 'Input');\r\n");
      out.write("            if (selectedInputContainer) {\r\n");
      out.write("                selectedInputContainer.style.display = 'block';\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 탭에 따라 제목 변경\r\n");
      out.write("            document.getElementById('tabTitle').textContent = getTabTitle(tabName);\r\n");
      out.write("\r\n");
      out.write("            // 현재 탭 설정\r\n");
      out.write("            currentTab = tabName;\r\n");
      out.write("            \r\n");
      out.write("            // 탭 변경 시 이전에 계산한 값을 표시\r\n");
      out.write("            var carbonEmissionElement = document.getElementById('carbonEmission');\r\n");
      out.write("            var treeConversionElement = document.getElementById('treeConversion');\r\n");
      out.write("\r\n");
      out.write("            if (tabResults[currentTab]) {\r\n");
      out.write("                carbonEmissionElement.textContent = tabResults[currentTab].carbonEmission.toFixed(2);\r\n");
      out.write("                treeConversionElement.textContent = tabResults[currentTab].treeConversion.toFixed(2);\r\n");
      out.write("            } else {\r\n");
      out.write("                carbonEmissionElement.textContent = '0.00';\r\n");
      out.write("                treeConversionElement.textContent = '0.00';\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 탭 -->\r\n");
      out.write("    <div id=\"tabContainer\" style=\"margin-top: 120px;\">\r\n");
      out.write("         <div class=\"tab electricity shadow-soft\" onclick=\"changeTab('electricity')\">전기</div>\r\n");
      out.write("        <div class=\"tab gas shadow-soft\" onclick=\"changeTab('gas')\">가스</div>\r\n");
      out.write("        <div class=\"tab water shadow-soft\" onclick=\"changeTab('water')\">수도</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 계산기 -->\r\n");
      out.write("    <div id=\"calculator\">\r\n");
      out.write("        <h2 id=\"tabTitle\"></h2>\r\n");
      out.write("\r\n");
      out.write("        <!-- 전기 사용량 입력창 -->\r\n");
      out.write("        <div class=\"usageInput electricityInput\">\r\n");
      out.write("            <label for=\"electricityUsage\">사용량 (kWh): </label>\r\n");
      out.write("            <input type=\"text\" id=\"electricityUsage\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 가스 사용량 입력창 -->\r\n");
      out.write("        <div class=\"usageInput gasInput\">\r\n");
      out.write("            <label for=\"gasUsage\">사용량(m^3): </label>\r\n");
      out.write("            <input type=\"text\" id=\"gasUsage\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 수도 사용량 입력창 -->\r\n");
      out.write("        <div class=\"usageInput waterInput\">\r\n");
      out.write("            <label for=\"waterUsage\">사용량(m^3): </label>\r\n");
      out.write("            <input type=\"text\" id=\"waterUsage\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 결과 표시창 -->\r\n");
      out.write("        <div id=\"result\">\r\n");
      out.write("            <p>탄소배출량: <span id=\"carbonEmission\">0</span> kg CO2</p>\r\n");
      out.write("            <p>나무 환산: <span id=\"treeConversion\">0</span> 그루</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 추가: 총 탄소발생량 및 총 나무환산 -->\r\n");
      out.write("		<div id=\"totalResult\">\r\n");
      out.write("		    <p>총 탄소발생량: <span id=\"totalCarbonEmission\">0</span> kg CO2</p>\r\n");
      out.write("		    <p>총 나무 환산: <span id=\"totalTreeConversion\">0</span> 그루</p>\r\n");
      out.write("		</div>\r\n");
      out.write("			\r\n");
      out.write("        <!-- 결과 계산 버튼 -->\r\n");
      out.write("        <button onclick=\"calculateResult();  saveResultToLocalStorage();\">계산</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        // 초기 실행 시 탭 변경 함수 호출\r\n");
      out.write("        changeTab(currentTab);\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("	<button class=\"btn-3d blue\" id=\"moveToReportPage\" >사용자 정보 입력 이동</button>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	    // 버튼 클릭 시 이벤트 처리\r\n");
      out.write("	    document.getElementById('moveToReportPage').addEventListener('click', function () {\r\n");
      out.write("	        // 새로운 페이지의 URL로 이동\r\n");
      out.write("	        window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/result'; // 이동하고자 하는 URL로 변경\r\n");
      out.write("	    });\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	// 로컬 스토리지에 값을 저장하는 함수\r\n");
      out.write("	function saveToLocalStorage(key, value) {\r\n");
      out.write("	    localStorage.setItem(key, JSON.stringify(value));\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	// 계산 결과를 로컬 스토리지에 저장\r\n");
      out.write("	function saveResultToLocalStorage() {\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	    // 다른 필요한 값들도 추가\r\n");
      out.write("	    var result = {\r\n");
      out.write("	    		electricityEmission: Math.round(electricityEmission * 100) / 100,\r\n");
      out.write("	    		gasEmission: Math.round(gasEmission * 100) / 100,\r\n");
      out.write("	    		waterEmission: Math.round(waterEmission * 100) / 100,\r\n");
      out.write("	    		totalCarbonEmission: Math.round(totalCarbonEmission * 100) / 100,\r\n");
      out.write("	    		totalTreeConversion: Math.round(totalTreeConversion * 100) / 100,\r\n");
      out.write("	        \r\n");
      out.write("	        // 다른 필요한 값들도 추가\r\n");
      out.write("	    };\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	    saveToLocalStorage('calculationResult', result);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!-- Footer-->\r\n");
      out.write("<footer\r\n");
      out.write("	class=\"d-flex pb-5 pt-6 pt-md-7 border-top border-light bg-primary\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4\">\r\n");
      out.write("				<p class=\"text-gray font-small m-0\">\r\n");
      out.write("				<h5>TEAM CARINA</h5>\r\n");
      out.write("				was created to raise awareness and contribute socially to the carbon\r\n");
      out.write("				neutrality issues facing humanity.\r\n");
      out.write("				</p>\r\n");
      out.write("				<ul class=\"d-flex list-unstyled mb-5 mb-lg-0\">\r\n");
      out.write("					<li class=\"mr-2\"><a href=\"https://me.go.kr/home/web/main.do\"><img\r\n");
      out.write("							src=\"resources/assets/img/brand/환경부.png\"></a></li>\r\n");
      out.write("					<li class=\"mr-2\"><a\r\n");
      out.write("						href=\"https://www.kcen.kr/USR_main2016.jsp??=MAIN/index\"><img\r\n");
      out.write("							src=\"resources/assets/img/brand/한국기후환경 네트워크.png\"></a></li>\r\n");
      out.write("					<li class=\"mr-2\"><a\r\n");
      out.write("						href=\"https://www.c-action.kr/web/index.html\"><img\r\n");
      out.write("							src=\"resources/assets/img/brand/기후행동 1.5.png\"></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-6 col-lg-2 mb-5 mb-lg-0\">\r\n");
      out.write("				<h5>CARINA</h5>\r\n");
      out.write("				<ul class=\"footer-links list-unstyled mt-2\">\r\n");
      out.write("					<li class=\"mb-1\"><a class=\"p-2\" target=\"_blank\"\r\n");
      out.write("						href=\"");
      if (_jspx_meth_c_005furl_005f17(_jspx_page_context))
        return;
      out.write("\">지역별 탄소 배출량</a></li>\r\n");
      out.write("					<li class=\"mb-1\"><a class=\"p-2\" target=\"_blank\"\r\n");
      out.write("						href=\"");
      if (_jspx_meth_c_005furl_005f18(_jspx_page_context))
        return;
      out.write("\">환경 MBTI</a></li>\r\n");
      out.write("					<li class=\"mb-1\"><a class=\"p-2\" target=\"_blank\"\r\n");
      out.write("						href=\"");
      if (_jspx_meth_c_005furl_005f19(_jspx_page_context))
        return;
      out.write("\">전력 예측 모델</a></li>\r\n");
      out.write("					<li><a class=\"p-2\" target=\"_blank\"\r\n");
      out.write("						href=\"");
      if (_jspx_meth_c_005furl_005f20(_jspx_page_context))
        return;
      out.write("\">탄소 시뮬레이터</a></li>\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-6 col-lg-2 mb-5 mb-lg-0\">\r\n");
      out.write("				<h5>게시판</h5>\r\n");
      out.write("				<ul class=\"footer-links list-unstyled mt-2\">\r\n");
      out.write("					<li><a class=\"p-2\" target=\"_blank\"\r\n");
      out.write("						href=\"");
      if (_jspx_meth_c_005furl_005f21(_jspx_page_context))
        return;
      out.write("\">자유 게시판</a></li>\r\n");
      out.write("					<li><a class=\"p-2\" target=\"_blank\"\r\n");
      out.write("						href=\"");
      if (_jspx_meth_c_005furl_005f22(_jspx_page_context))
        return;
      out.write("\">실천 일지</a></li>\r\n");
      out.write("					<li><a class=\"p-2\" target=\"_blank\"\r\n");
      out.write("						href=\"");
      if (_jspx_meth_c_005furl_005f23(_jspx_page_context))
        return;
      out.write("\">환경 뉴스</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-12 col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("				<h5>연락처</h5>\r\n");
      out.write("				<p class=\"text-gray font-small mt-2\">주소: 대전시 서구 계룡로 491번길 86(둔산동\r\n");
      out.write("					1221번지) 전화번호: 042-471-9222 팩스: 042-471-9223</p>\r\n");
      out.write("\r\n");
      out.write("				<p class=\"text-gray font-small m-0\">\r\n");
      out.write("					We’ll never share your details. See our <a class=\"text-black\"\r\n");
      out.write("						href=\"#\">Privacy Policy</a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr class=\"my-5\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col\">\r\n");
      out.write("				<a href=\"https://themesberg.com\" target=\"_blank\"\r\n");
      out.write("					class=\"d-flex justify-content-center\"><img\r\n");
      out.write("					src=\"resources/assets/img/brand/carina_logo.png\" height=\"100\"\r\n");
      out.write("					class=\"mb-3\" alt=\"CARINA Logo\"></a>\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"d-flex text-center justify-content-center align-items-center\"\r\n");
      out.write("					role=\"contentinfo\">\r\n");
      out.write("					<p class=\"font-weight-normal font-small mb-0\">\r\n");
      out.write("						Copyright © CARINA <span class=\"current-year\">2023</span>. All\r\n");
      out.write("						rights reserved.\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/popper.js/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/headroom.js/dist/headroom.min.js\"></script>\r\n");
      out.write("<!-- Vendor JS -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/onscreen/dist/on-screen.umd.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/nouislider/distribute/nouislider.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/waypoints/lib/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/jarallax/dist/jarallax.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/jquery.counterup/jquery.counterup.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/jquery-countdown/dist/jquery.countdown.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/prismjs/prism.js\"></script>\r\n");
      out.write("<script async defer=\"defer\" src=\"https://buttons.github.io/buttons.js\"></script>\r\n");
      out.write("<!-- Neumorphism JS -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/neumorphism.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/inc/top.jsp(77,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/inc/top.jsp(92,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/carbon");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/inc/top.jsp(95,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/mbti");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/inc/top.jsp(98,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/simulater ");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/inc/top.jsp(106,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/powerPrediction");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/inc/top.jsp(108,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/solution");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/inc/top.jsp(116,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/actboard");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/inc/top.jsp(117,41) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/news");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/inc/top.jsp(120,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/freeboard");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/inc/top.jsp(129,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.login or empty sessionScope.login.memId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<!-- 로그인되어 있지 않은 경우 -->\r\n");
          out.write("				<a href=\"");
          if (_jspx_meth_c_005furl_005f9(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\" target=\"_self\"\r\n");
          out.write("					class=\"btn btn-primary1 text-secondary d-none d-md-inline-block mr-2\">로그인</a>\r\n");
          out.write("				<a href=\"");
          if (_jspx_meth_c_005furl_005f10(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\" target=\"_self\"\r\n");
          out.write("					class=\"btn btn-primary1 text-secondary d-none d-md-inline-block mr-2\">회원\r\n");
          out.write("					가입</a>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/inc/top.jsp(132,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/loginView");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/inc/top.jsp(134,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/registView");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/inc/top.jsp(139,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.login and sessionScope.login.memId eq 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<!-- 아이디가 'admin'인 경우 -->\r\n");
          out.write("				<a href=\"");
          if (_jspx_meth_c_005furl_005f11(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\" target=\"_self\"\r\n");
          out.write("					class=\"btn btn-primary1 text-secondary d-none d-md-inline-block mr-2\">로그\r\n");
          out.write("					아웃</a>\r\n");
          out.write("				<a href=\"");
          if (_jspx_meth_c_005furl_005f12(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\" target=\"_self\"\r\n");
          out.write("					class=\"btn btn-primary1 text-secondary d-none d-md-inline-block mr-2\">관리자</a>\r\n");
          out.write("\r\n");
          out.write("<!-- 					class=\"btn btn-primary1 text-secondary d-none d-md-inline-block mr-2\">내정보</a> -->\r\n");
          out.write("				");
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/inc/top.jsp(142,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/logout");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f12 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f12_reused = false;
    try {
      _jspx_th_c_005furl_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/inc/top.jsp(145,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f12.setValue("/admin");
      int _jspx_eval_c_005furl_005f12 = _jspx_th_c_005furl_005f12.doStartTag();
      if (_jspx_th_c_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f12);
      _jspx_th_c_005furl_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f12, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/inc/top.jsp(152,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.login and sessionScope.login.memId ne 'admin' and not fn:containsIgnoreCase(sessionScope.login.memId, 'kakao')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<!-- 로그인되어 있고 일반 사용자인 경우 (카카오 아이디 아닌 경우) -->\r\n");
          out.write("				<a href=\"");
          if (_jspx_meth_c_005furl_005f13(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\" target=\"_self\"\r\n");
          out.write("					class=\"btn btn-primary1 text-secondary d-none d-md-inline-block mr-2\">로그\r\n");
          out.write("					아웃</a>\r\n");
          out.write("				<a href=\"");
          if (_jspx_meth_c_005furl_005f14(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\" target=\"_self\"\r\n");
          out.write("					class=\"btn btn-primary1 text-secondary d-none d-md-inline-block mr-2\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.login.memNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("					님</a>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f13(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f13 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f13_reused = false;
    try {
      _jspx_th_c_005furl_005f13.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/inc/top.jsp(155,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f13.setValue("/logout");
      int _jspx_eval_c_005furl_005f13 = _jspx_th_c_005furl_005f13.doStartTag();
      if (_jspx_th_c_005furl_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f13);
      _jspx_th_c_005furl_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f13, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f14(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f14 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f14_reused = false;
    try {
      _jspx_th_c_005furl_005f14.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f14.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/inc/top.jsp(158,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f14.setValue("/mypage");
      int _jspx_eval_c_005furl_005f14 = _jspx_th_c_005furl_005f14.doStartTag();
      if (_jspx_th_c_005furl_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f14);
      _jspx_th_c_005furl_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f14, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/inc/top.jsp(163,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.login and fn:containsIgnoreCase(sessionScope.login.memId, 'kakao')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<!-- 카카오 아이디인 경우 -->\r\n");
          out.write("				<a href=\"");
          if (_jspx_meth_c_005furl_005f15(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("\" target=\"_self\"\r\n");
          out.write("					class=\"btn btn-primary1 text-secondary d-none d-md-inline-block mr-2\">\r\n");
          out.write("					로그아웃</a>\r\n");
          out.write("				<a href=\"");
          if (_jspx_meth_c_005furl_005f16(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("\" target=\"_self\"\r\n");
          out.write("					class=\"btn btn-primary1 text-secondary d-none d-md-inline-block mr-2\">내정보</a>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f15(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f15 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f15_reused = false;
    try {
      _jspx_th_c_005furl_005f15.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f15.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/inc/top.jsp(166,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f15.setValue("/kakaologout");
      int _jspx_eval_c_005furl_005f15 = _jspx_th_c_005furl_005f15.doStartTag();
      if (_jspx_th_c_005furl_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f15);
      _jspx_th_c_005furl_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f15, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f16(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f16 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f16_reused = false;
    try {
      _jspx_th_c_005furl_005f16.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f16.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/inc/top.jsp(169,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f16.setValue("/mypage");
      int _jspx_eval_c_005furl_005f16 = _jspx_th_c_005furl_005f16.doStartTag();
      if (_jspx_th_c_005furl_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f16);
      _jspx_th_c_005furl_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f16, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f16_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f17 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f17_reused = false;
    try {
      _jspx_th_c_005furl_005f17.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f17.setParent(null);
      // /WEB-INF/inc/footer.jsp(30,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f17.setValue("/carbon");
      int _jspx_eval_c_005furl_005f17 = _jspx_th_c_005furl_005f17.doStartTag();
      if (_jspx_th_c_005furl_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f17);
      _jspx_th_c_005furl_005f17_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f17, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f17_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f18(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f18 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f18_reused = false;
    try {
      _jspx_th_c_005furl_005f18.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f18.setParent(null);
      // /WEB-INF/inc/footer.jsp(32,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f18.setValue("/mbti");
      int _jspx_eval_c_005furl_005f18 = _jspx_th_c_005furl_005f18.doStartTag();
      if (_jspx_th_c_005furl_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f18);
      _jspx_th_c_005furl_005f18_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f18, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f18_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f19(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f19 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f19_reused = false;
    try {
      _jspx_th_c_005furl_005f19.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f19.setParent(null);
      // /WEB-INF/inc/footer.jsp(34,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f19.setValue("/powerPrediction");
      int _jspx_eval_c_005furl_005f19 = _jspx_th_c_005furl_005f19.doStartTag();
      if (_jspx_th_c_005furl_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f19);
      _jspx_th_c_005furl_005f19_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f19, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f19_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f20(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f20 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f20_reused = false;
    try {
      _jspx_th_c_005furl_005f20.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f20.setParent(null);
      // /WEB-INF/inc/footer.jsp(36,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f20.setValue("/simulater ");
      int _jspx_eval_c_005furl_005f20 = _jspx_th_c_005furl_005f20.doStartTag();
      if (_jspx_th_c_005furl_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f20);
      _jspx_th_c_005furl_005f20_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f20, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f20_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f21(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f21 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f21_reused = false;
    try {
      _jspx_th_c_005furl_005f21.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f21.setParent(null);
      // /WEB-INF/inc/footer.jsp(44,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f21.setValue("/freeboard");
      int _jspx_eval_c_005furl_005f21 = _jspx_th_c_005furl_005f21.doStartTag();
      if (_jspx_th_c_005furl_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f21);
      _jspx_th_c_005furl_005f21_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f21, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f21_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f22(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f22 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f22_reused = false;
    try {
      _jspx_th_c_005furl_005f22.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f22.setParent(null);
      // /WEB-INF/inc/footer.jsp(46,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f22.setValue("/actdetail");
      int _jspx_eval_c_005furl_005f22 = _jspx_th_c_005furl_005f22.doStartTag();
      if (_jspx_th_c_005furl_005f22.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f22);
      _jspx_th_c_005furl_005f22_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f22, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f22_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f23(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f23 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f23_reused = false;
    try {
      _jspx_th_c_005furl_005f23.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f23.setParent(null);
      // /WEB-INF/inc/footer.jsp(48,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f23.setValue("/news");
      int _jspx_eval_c_005furl_005f23 = _jspx_th_c_005furl_005f23.doStartTag();
      if (_jspx_th_c_005furl_005f23.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f23);
      _jspx_th_c_005furl_005f23_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f23, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f23_reused);
    }
    return false;
  }
}
